### ISSUE TITLE
Add prefix option

### ISSUE THREAD

**Issue by rien333** [emacsfodder/move-text#14]
It would be nice to be able to `C-u` and then hit a number for how far down you want to move some line/region (I would be okay with implementing this myself, but it will probably take a while before I learn emacs lips)

**Comment by jasonm23** [comment]
That's a good point, it _should_ be part of everything!

I'll see if I can quickly put it in.

**Comment by jasonm23** [comment]
Please verify with your Emacs session, move text should be working with C-u (possibly only on region though)

**Comment by jasonm23** [comment]
@rien333 classifying this as a bug because this is intended behavior already.

Thanks for raising the issue.

**Comment by jasonm23** [comment]
Looks like I messed up my test of region move.  Prefix is working ok there.

Single line isn't working yet.

**Comment by jasonm23** [comment]
Fixed in @daaa5c3
