### ISSUE TITLE
Suggestion: move region left / right by semantic unit

### ISSUE THREAD

**Issue by DmitriR** [emacsfodder/move-text#15]
... depending on what is selected. A word, sentence, (code block, ... - possibly depending on the mode).

**Comment by jasonm23** [comment]
Check out rejeep's text moving package. (I forget what it's called!)

It does left / right move IIRC 

Move text will not have this feature though.

**Comment by jasonm23** [comment]
Check out rejeep's text moving package. (I forget what it's called!)

It does left / right move IIRC 

Move text will not have this feature though.

**Comment by DmitriR** [comment]
https://github.com/rejeep/drag-stuff.el

**Comment by jasonm23** [comment]
That's the one
