### ISSUE TITLE
Can`nt work in Elisp mode

### ISSUE THREAD

**Issue by boern** [emacsfodder/move-text#16]
Hi,all:
      When I use " M+up/down " to move the line in emacs init.el ,it can`nt work,and make a error, I think that`s key conflict.

The following is the error msg:
--------------------------------------------------------------------------------------------------------
 entered--Lisp error: (error "Can’t splice top level.")
  signal(error ("Can’t splice top level."))
  error("Can't splice top level.")
  paredit-splice-sexp((4))
  paredit-splice-sexp-killing-backward(nil)
  funcall-interactively(paredit-splice-sexp-killing-backward nil)
  call-interactively(paredit-splice-sexp-killing-backward nil nil)
  command-execute(paredit-splice-sexp-killing-backward)

So, how to solve the issue?

**Comment by jasonm23** [comment]
You have a conflict with paredit.  I'd recommend doing transpose-sexp to get the movement you're looking for.
