### ISSUE TITLE
Cursor randomly moves after save-buffer

### ISSUE THREAD

**Issue by ghowoo** [emacsfodder/move-text#20]
For several days, I had experienced this weird behavior that sometimes I save-buffer using the function or using key-binding (C-x C-s), the cursor moves to somewhere far away in the buffer. It happens in the ESS-R mode. I have tried to disable save-place-mode, but doesn't work until I commented the following line:

(add-hook 'before-save-hook 'delete-trailing-whitespace)

I'm not sure if it is related to the move-text package, or maybe just related to save-hook because somebody mentioned that to check save-hook. Link here:
https://www.reddit.com/r/emacs/comments/kt1oml/can_anybody_help_me_pinpoint_the_cause_for_cursor/

Thanks.

**Comment by jasonm23** [comment]
Sounds like it's related to save hook.

Weird though.  I think can close this after you debug your config
