### ISSUE TITLE
org-meta-up

### ISSUE THREAD

**Issue by madorian** [emacsfodder/move-text#29]
Will this interfere with org-meta-up, or how do they work together?;)

**Comment by jasonm23** [comment]
Local mode key binding maps take precedence.

**Comment by madorian** [comment]
Does that mean that in org-mode buffers, it won't work, then?

**Comment by jasonm23** [comment]
Try it.

But to explain the previous comment, when you switch to a mode (like Org) the keymap for that mode, _should_ take precedence.

**Comment by jasonm23** [comment]
Recommendation: open issues for things that you experience to be broken.

We'll figure out what to do based on actual conditions.
