### ISSUE TITLE
Don't move cursor at beginning of line

### ISSUE THREAD

**Issue by mekeor** [emacsfodder/move-text#8]
When moving a line, the cursor is being moved to its beginning. It'd be nice if the cursor stayed where it was. This is due to `transpose-lines`. Instead, I'd suggest to use the idea of the other code snippet at https://www.emacswiki.org/emacs/MoveLine.

**Comment by jasonm23** [comment]
I will look into this later.  You are welcome to submit a patch / pull request too.

**Comment by mekeor** [comment]
The issue doesn't seem to be solved to me, is it?

**Comment by jasonm23** [comment]
The behaviour isnt what i want in move-text

**Comment by jasonm23** [comment]
Ill accept a pr that allows this as optional behaviour.

**Comment by jasonm23** [comment]
Btw you can attach a gif to the thread showing whats wrong, and what you'd like.

**Comment by jasonm23** [comment]
Dude, sorry about closing this one.  This is definitely a bug, I thought you wanted a change from the expected behavior (as seen in the GIF.)

Reopening.

**Comment by jasonm23** [comment]
Fixed in df534f3 (v2.0.6)
