### ISSUE TITLE
M-down (move-text-down) returns error: Symbol's function definition is void: save-mark-and-excursion

### ISSUE THREAD

**Issue by kspurgin** [emacsfodder/move-text#9]
M-up is working as expected. 

When I have the cursor in a line (no region selected) and do M-down: 

- The line the cursor was in is NOT moved down
- The cursor jumps to the bottom of the buffer
- In the minibuffer, I see: "Symbol's function definition is void: save-mark-and-excursion"
- In *Messages* I find: move-text--last-line-is-just-newline: Symbol's function definition is void: save-mark-and-excursion

I just upgraded the package from MELPA. Realized the above was all in Emac 24.something I was still using. 

Upgraded to Emacs 25 and am seeing the same behavior, with a slightly different message: 
move-text--last-line-is-just-newline: Invalid function: save-mark-and-excursion

Let me know if there's any more info I can provide.

**Comment by jasonm23** [comment]
Please send the message printed by:

    M-x version

**Comment by kspurgin** [comment]
GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17

**Comment by jasonm23** [comment]
Could you try :

    C-h f save-mark-and-excursion

**Comment by jasonm23** [comment]
It should give you a help/documentation page for `save-mark-and-excursion`

**Comment by jasonm23** [comment]
Please try recompiling your elpa packages.

The function is new for Emacs 24.5 (IIRC) perhaps some old byte code (elc) is still active.

**Comment by wnr** [comment]
I have this problem too. Running `C-h f save-mark-and-excursion` tells me:

```
save-mark-and-excursion is a Lisp macro in ‘simple.el’.

(save-mark-and-excursion &rest BODY)

Like ‘save-excursion’, but also save and restore the mark state.
This macro does what ‘save-excursion’ did before Emacs 25.1.
```

**Comment by wnr** [comment]
Yes, now it works. Thanks!
